name: Check style

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check style
      run: |
        npx standard
